spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: testdb
    password: psw1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
